### ISSUE TITLE
examples are missing addons.make

### ISSUE THREAD

**Issue by ofZach** [NickHardeman/ofxSvgLoader#1]
this issue is no biggie!  I just made them by hand, but because these project use osx10.8 sdk which is kind of old by now they need to be updated on machines that don't have that sdk.  Adding addons.make helps the PG know what to add.

**Comment by NickHardeman** [comment]
Thanks Zach. I have finally upgraded from 10.8 to 10.9 and I can work on adding the addons.make files. If you already have them, I can merge them in if you send a pull request.

**Comment by NickHardeman** [comment]
Finally added them over a year later. :)
