### ISSUE TITLE
how to ignore color attribute?

### ISSUE THREAD

**Issue by dimitre** [NickHardeman/ofxSvgLoader#4]
Hey @NickHardeman thanks for this addon, it is great to be able to parse SVG by group names. 
It would be great to have a way of disabling colors in the SVG so it can draw with current color, in the likes of
```c++
void ofxAssimpModelLoader::disableColors()
```
Cheers!

**Comment by NickHardeman** [comment]
Hi @dimitre,
Thank you for the suggestion.
I added these functions to allow ignoring of the svg colors per group or individual element.
https://github.com/NickHardeman/ofxSvgLoader/blob/972adc3b8b4a3bdd52f0f5f38ac2d312931a7cc1/src/ofxSvgGroup.h#L70-L71

**Comment by dimitre** [comment]
That's beautiful! Already working here. This addon is great it should be on OFW core :)
